@startuml
skinparam groupInheritance 2

class Main {
  -Carte carte
  -List<UniteAbstract> listeUnite
  -Inventaire inventaire
  -int tour

  +Main()
  +void run()
  +void main()
  +void question()
  +void boucle()
  +void clearConsole()
  +void tour()
}

class Inventaire {
  -Map<ResourceType, Integer> resources
  -{static} Inventory instance

  +{static} Inventory getInstance()
  +void ajouterRessource( type,quantite)
  +void retirerRessource( type,quantite)
  +boolean possedeRessource( type,quantite)
  +int get( type)
  +void afficher()
}

class Carte {
  -int largeur
  -int hauteur
  -Case[][] cases
  -Carte instance;

  +Carte getInstance()
  +Carte(int largeur, int hauteur)
  +void afficher()
  +void travailler()
  +void deplacerUnite()
  +Case getCase(x,y)
  +int getX()
  +int getY()
}

class Case {
  -int x
  -int y
  -int Ressource ressource
  -UniteAbstract unite

  +Case(x,y)
  +void ConsomerRessource(outil);
  +void afficher()
  +int getX()
  +int getY()
  +Ressource getRessource()
  +UniteAbstract getUnite()
  +UniteAbstract setUnite(unite)
}

enum TypeResource {
  +{field} BOIS(7,"B","du bois")
  +{field} OR(8,"O","de l'or")
  +{field} PIERRE(5, "P","de la pierre"),
  +{field} NOURRITURE(30,"N","de la nourriture"),
  +{field} RIEN(0,"",""),

  -int tailleMax
  -String symbole
  -String recolte

  +TypeRessource( int tailleMax, String symbole, String recolte)
  +int getTailleMax()
  +String getSymbole()
  +String getRecolte()
}
enum TypeTravail {
  +{field} FERMIER (NOURRITURE)
  +{field} BUCHEROON (BOIS)
  +{field} MINEUR (OR,PIERRE)

  -{final} TypeRessource[] typeRessource

  +TypeTravail(TypeRessource)
  +boolean estBonOutil(TypeRessource)
  +TypeRessource[] getTypeRessource()
}
abstract class unite.UniteAbstract{
  -String nom
  -int vitesse
  -int cout
  -Case position
  -Outil outil;

  +{abstract} void afficher()
  +{abstract} void travailler()
  +Outil getOutil()
  +void setOutil(outil)
  +void deplacer()
  +void deplacerDeUnVersDirection(Direction direction)
  +Case ressouceLaPlusProche(TypeRessource[] typeRessources)
  +Direction cheminLePlusCourt(Case destination)
  +void teleporter(x,y)
  +Case getPosition()
  +void setPosition(position)
  +int getX()
  +int getY()
  +int getVitesse()
  +void setVitesse(vitesse)
  +int getCout()
  +void setCout(int cout)

}

class unite.UniteGroupe extends unite.UniteAbstract {
  -List<UniteAbstract> unites

  +UniteGroupe(UniteAbstract unite)
  +void travailler()
  +int getVitesse()
  +deplacerDeUnVersDirection(Direction direction)
  +void afficher()
  +Outil getOutil()
  +addUnite(UniteAbstract unite)
  +Case getPosition()
  +int getX()
  +int getY()
}

class unite.UniteSimple extends unite.UniteAbstract {
   boolean expert
   int exp;

   +UniteSimple(nom, vitesse, cout, position)
   +void travailler()
   +void deplacer()
   +void afficher()
   +boolean isExpert()
   +void levelUp()
   +void checkExpert()

}

class unite.UniteMonte extends unite.UniteAbstract {
  -UniteSimple unite

  +void seDeplacer()
}

class Outil{
  -int niveau
  -TypeTravail type

  +Outil(typeTravail)
  +boolean estBonOutil(TypeRessource)
  +TypeRessource[] getTypeRessource()
  +void afficher()
  +void ameliorer()
  +int getNiveau()
  +TypeTravail getTypeTravail()
}
class Ressource{
  -TypeRessource type
  -int quantite

  Ressource(type)
}
enum Direction {
  +{field} HAUT
  +{field} BAS
  +{field} GAUCHE
  +{field} DROITE
}

@enduml